## Predictions on Global Terrorist Database 2013 to 2016

## Importing the libraies

In [98]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [99]:
df = pd.read_excel('C:/Users/ddddd/Downloads/Gtd/gtd_13to16_0617dist.xlsx')
print(df)

            eventid  iyear  imonth  iday           approxdate  extended  \
0      201301010001   2013       1     1                  NaN         0
1      201301010002   2013       1     1                  NaN         0
2      201301010003   2013       1     1                  NaN         0
3      201301010004   2013       1     1                  NaN         0
4      201301010005   2013       1     1                  NaN         0
5      201301010006   2013       1     1                  NaN         0
6      201301010007   2013       1     1                  NaN         0
7      201301010008   2013       1     1                  NaN         0
8      201301010009   2013       1     1                  NaN         0
9      201301010012   2013       1     1                  NaN         1
10     201301010013   2013       1     1                  NaN         0
11     201301010014   2013       1     1                  NaN         0
12     201301010015   2013       1     1                  NaN         0
13     201301010016   2013       1     1                  NaN         0
14     201301010017   2013       1     1                  NaN         0
15     201301010020   2013       1     1                  NaN         0
16     201301010022   2013       1     1                  NaN         0
17     201301010023   2013       1     1                  NaN         0
18     201301010024   2013       1     1                  NaN         0
19     201301010025   2013       1     1                  NaN         0
20     201301010026   2013       1     1                  NaN         0
21     201301010027   2013       1     1                  NaN         0
22     201301010029   2013       1     1                  NaN         0
23     201301010033   2013       1     1                  NaN         0
24     201301010036   2013       1     1                  NaN         0
25     201301010037   2013       1     1                  NaN         0
26     201301020001   2013       1     1                  NaN         0
27     201301020002   2013       1     2                  NaN         0
28     201301020004   2013       1     2                  NaN         0
29     201301020005   2013       1     3                  NaN         0
...             ...    ...     ...   ...                  ...       ...
57166  201612310011   2016      12    31                  NaN         0
57167  201612310012   2016      12    31                  NaN         0
57168  201612310013   2016      12    30                  NaN         0
57169  201612310014   2016      12    31                  NaN         0
57170  201612310015   2016      12    31                  NaN         0
57171  201612310016   2016      12    31                  NaN         0
57172  201612310017   2016      12    31                  NaN         0
57173  201612310019   2016      12    31                  NaN         0
57174  201612310022   2016      12    31  2016-12-31 00:00:00         0
57175  201612310023   2016      12    31  2016-12-31 00:00:00         0
57176  201612310024   2016      12    31                  NaN         0
57177  201612310025   2016      12    31  2016-12-31 00:00:00         0
57178  201612310026   2016      12    31                  NaN         0
57179  201612310027   2016      12    31                  NaN         0
57180  201612310028   2016      12    31                  NaN         0
57181  201612310029   2016      12    31                  NaN         0
57182  201612310030   2016      12    31                  NaN         0
57183  201612310031   2016      12    31                  NaN         0
57184  201612310033   2016      12    31                  NaN         0
57185  201612310034   2016      12    31                  NaN         0
57186  201612310035   2016      12    31                  NaN         0
57187  201612310036   2016      12    31                  NaN         0
57188  201612310037   2016      12    31                  NaN         0
57189  201612310038   2016      12    30                  NaN         0
57190  201612310039   2016      12    31  2016-12-31 00:00:00         0
57191  201612310040   2016      12    31                  NaN         0
57192  201612310042   2016      12    31                  NaN         0
57193  201612310043   2016      12    31                  NaN         1
57194  201612310044   2016      12    31                  NaN         0
57195  201701270001   2016      12    30                  NaN         0

       resolution  country                       country_txt  region  \
0             NaN      153                          Pakistan       6
1             NaN       95                              Iraq      10
2             NaN       95                              Iraq      10
3             NaN       95                              Iraq      10
4             NaN      153                          Pakistan       6
5             NaN      153                          Pakistan       6
6             NaN      153                          Pakistan       6
7             NaN      153                          Pakistan       6
8             NaN      153                          Pakistan       6
9             NaN      147                           Nigeria      11
10            NaN      153                          Pakistan       6
11            NaN      153                          Pakistan       6
12            NaN       95                              Iraq      10
13            NaN       95                              Iraq      10
14            NaN       95                              Iraq      10
15            NaN       92                             India       6
16            NaN       95                              Iraq      10
17            NaN       95                              Iraq      10
18            NaN      153                          Pakistan       6
19            NaN      153                          Pakistan       6
20            NaN      153                          Pakistan       6
21            NaN      160                       Philippines       5
22            NaN      147                           Nigeria      11
23            NaN      153                          Pakistan       6
24            NaN       95                              Iraq      10
25            NaN       95                              Iraq      10
26            NaN      153                          Pakistan       6
27            NaN      153                          Pakistan       6
28            NaN      147                           Nigeria      11
29            NaN        4                       Afghanistan       6
...           ...      ...                               ...     ...
57166         NaN      160                       Philippines       5
57167         NaN       19                        Bangladesh       6
57168         NaN      153                          Pakistan       6
57169         NaN      173                      Saudi Arabia      10
57170         NaN        4                       Afghanistan       6
57171         NaN       34                           Burundi      11
57172         NaN      153                          Pakistan       6
57173         NaN       92                             India       6
57174         NaN        4                       Afghanistan       6
57175         NaN        4                       Afghanistan       6
57176         NaN      147                           Nigeria      11
57177         NaN       95                              Iraq      10
57178         NaN       95                              Iraq      10
57179         NaN       95                              Iraq      10
57180         NaN       95                              Iraq      10
57181         NaN       95                              Iraq      10
57182         NaN       95                              Iraq      10
57183         NaN       95                              Iraq      10
57184         NaN      153                          Pakistan       6
57185         NaN        4                       Afghanistan       6
57186         NaN        4                       Afghanistan       6
57187         NaN        4                       Afghanistan       6
57188         NaN        4                       Afghanistan       6
57189         NaN        4                       Afghanistan       6
57190         NaN        4                       Afghanistan       6
57191         NaN      146                             Niger      11
57192         NaN      160                       Philippines       5
57193         NaN      229  Democratic Republic of the Congo      11
57194         NaN      130                            Mexico       1
57195         NaN      195                             Sudan      11

                             ...                          \
0                            ...
1                            ...
2                            ...
3                            ...
4                            ...
5                            ...
6                            ...
7                            ...
8                            ...
9                            ...
10                           ...
11                           ...
12                           ...
13                           ...
14                           ...
15                           ...
16                           ...
17                           ...
18                           ...
19                           ...
20                           ...
21                           ...
22                           ...
23                           ...
24                           ...
25                           ...
26                           ...
27                           ...
28                           ...
29                           ...
...                          ...
57166                        ...
57167                        ...
57168                        ...
57169                        ...
57170                        ...
57171                        ...
57172                        ...
57173                        ...
57174                        ...
57175                        ...
57176                        ...
57177                        ...
57178                        ...
57179                        ...
57180                        ...
57181                        ...
57182                        ...
57183                        ...
57184                        ...
57185                        ...
57186                        ...
57187                        ...
57188                        ...
57189                        ...
57190                        ...
57191                        ...
57192                        ...
57193                        ...
57194                        ...
57195                        ...

                                                addnotes  \
0                                                    NaN
1      Casualty numbers for this incident represent a...
2      Casualty numbers for this incident represent a...
3      Casualty numbers for this incident conflict ac...
4                                                    NaN
5                                                    NaN
6                                                    NaN
7                                                    NaN
8                                                    NaN
9                                                    NaN
10     There is doubt that this incident meets terror...
11                                                   NaN
12                                                   NaN
13                                                   NaN
14                                                   NaN
15                                                   NaN
16                                                   NaN
17                                                   NaN
18                                                   NaN
19                                                   NaN
20                                                   NaN
21                                                   NaN
22                                                   NaN
23                                                   NaN
24     Casualty numbers for this incident conflict ac...
25                                                   NaN
26                                                   NaN
27                                                   NaN
28                                                   NaN
29                                                   NaN
...                                                  ...
57166                                                NaN
57167                                                NaN
57168                                                NaN
57169                                                NaN
57170  The victims included Nazia. Casualty numbers c...
57171                                                NaN
57172                                                NaN
57173                                                NaN
57174                                                NaN
57175                                                NaN
57176                                                NaN
57177                                                NaN
57178                                                NaN
57179  Casualty numbers represent a division of the t...
57180  Casualty numbers represent a division of the t...
57181  Casualty numbers conflict across sources. Foll...
57182                                                NaN
57183                                                NaN
57184                                                NaN
57185  Casualty figures represent a division of the t...
57186  Casualty figures represent a division of the t...
57187  Casualty figures represent a division of the t...
57188  Casualty figures represent a division of the t...
57189  The victims included Commander Shakoor, Noorul...
57190                                                NaN
57191                                                NaN
57192                                                NaN
57193                                                NaN
57194  There is doubt that this incident meets terror...
57195  There is doubt that this incident meets terror...

                                                  scite1  \
0      "Explosive device defused in Bannu," The News ...
1      "Deadly bombing leaves destruction in Kirkuk,"...
2      "Deadly bombing leaves destruction in Kirkuk,"...
3      "2 cops wounded by explosion mid Kirkuk," Aswa...
4      "Tragedy averted: 5kg   bomb defused   near po...
5      "BDS defuses two bombs in Orangi and Steel Tow...
6      "Two officers, driver shot dead," Plus News Pa...
7      "Two officers, driver shot dead," Plus News Pa...
8      "70 kg bomb defused in Peshawar," Free Press J...
9      "Police Rescue Delta Varsity's Official From K...
10     "Policeman gunned down in SITE," Plus News Pak...
11     "Charity workers shot dead returning from girl...
12     "3 cops wounded, officer's house exploded in T...
13     "3 cops wounded, officer's house exploded in T...
14     "3 cops wounded, officer's house exploded in T...
15     "Two more bombs found in Jaisalmer," The Times...
16     "6 people killed in Iraq's violence," Xinhua N...
17     "6 people killed in Iraq's violence," Xinhua N...
18     "Two girl students killed in Bara rocket hit,"...
19     "Truck driver injured in gun attack," Daily Ti...
20     "3 killed in NWA blast, shelling," Daily The P...
21     "Philippines anger at logging ban murder," Qat...
22     "Nigerian forces kill 13 militants," CNN, Janu...
23     "4 killed, 50 injured as bomb goes off near MQ...
24     "6 people killed in Iraq's violence," Xinhua N...
25     "6 people killed in Iraq's violence," Xinhua N...
26     "Attack: Worker's hujra destroyed by twin blas...
27     "Instilling terror: Yet another explosion in U...
28     "Seven dead in Nigerian army clash with insurg...
29     "Danish soldier killed in Afghanistan: ministr...
...                                                  ...
57166  "Philippines: BIFF attacks soldiers in North C...
57167  "Ruling party lawmaker shot dead in Bangladesh...
57168  "Suicide attack foiled in Rahim Yar Khan; two ...
57169  "Rebel fire from Yemen kills Saudi soldier," T...
57170  "Wounded bride: All my dreams shattered," Pajh...
57171  "Grenade explosion injures 8 in church in Buru...
57172  "ANP leader Rahim Barakazi killed in Peshawar,...
57173  "Bomb found at Imphal, hospital closed down," ...
57174  "Farah ALP officer wounded in gun attack," Paj...
57175  "Afghanistan: Nangarhar, Logar Clashes Result ...
57176  "Nigerian girl, 10, used in suicide bomb attac...
57177  "Iraq: Security Roundup 1900 GMT 31 December 2...
57178  "Double bomb attack hits crowded Baghdad marke...
57179  "Double bomb attack hits crowded Baghdad marke...
57180  "Double bomb attack hits crowded Baghdad marke...
57181  "Reuters: Baghdad blasts kill 29 as Mosul figh...
57182  "Update: Baghdad bomb attacks kill 30 at eve o...
57183  "CTS destroys 4 car bombs in eastern Mosul," I...
57184  "Two FC Balochistan personnel shot dead in Now...
57185  "Jawzjan clash leaves 2 rebels dead, 8 wounded...
57186  "Jawzjan clash leaves 2 rebels dead, 8 wounded...
57187  "Jawzjan clash leaves 2 rebels dead, 8 wounded...
57188  "Jawzjan clash leaves 2 rebels dead, 8 wounded...
57189  "Afghansitan: Blast in Jowzjan Province Kills ...
57190  "Program Summary: Afghanistan-Pul-e Alam Zinat...
57191  "15 soldiers killed, 19 injured in Niger terro...
57192  "AFP braces for more BIFF attacks in ARMM," Ma...
57193  "DRC Armed Forces Dislodge Ugandan LRA Rebels ...
57194  "Gunmen shoot at home of Mexican indigenous ri...
57195  "Rebels To Blame For Nierteti Killing: Central...

                                                  scite2  \
0                                                    NaN
1           "Iraq bomb kills one," ITN, January 2, 2013.
2           "Iraq bomb kills one," ITN, January 2, 2013.
3      "Iraqi forces arrest al-Qaeda terrorists," IRI...
4      "BDS defuses two bombs in Orangi and Steel Tow...
5      "Bombs defused in Orangi, Steel Town," The New...
6                                                    NaN
7                                                    NaN
8      "Blast in Jamrud damages house of anti-polio w...
9      "Varsity Staff Kidnapped in Delta," Vanguard, ...
10                                                   NaN
11     "MILITANTS GUN DOWN 7 AID WORKERS IN PAKISTAN,...
12     "3 cops wounded, officer's house exploded in T...
13     "3 cops wounded, officer's house exploded in T...
14                                                   NaN
15                                                   NaN
16                                                   NaN
17                                                   NaN
18     "Two girl students killed in Bara rocket hit,"...
19                                                   NaN
20     "Three killed in NWA blast, shelling," The New...
21     "CENRO official shot dead in Quirino," ABS-CBN...
22     "Nigerian army says 14 die in gun battle with ...
23     "Pakistan arrests five over polio killings:   ...
24     "A soldier killed ,two others injured ,center ...
25                                                   NaN
26     "Blast in Jamrud damages house of anti-polio w...
27     "Another explosion in Peshawar varsity," Front...
28     "Gunmen and security forces clash in Nigeria, ...
29     "Danish soldier killed by explosion in Afghani...
...                                                  ...
57166                                                NaN
57167  "Liton murder: PM blames Jamaat," Bangladesh D...
57168                                                NaN
57169  "Saudi Soldier killed due to rebel fire from Y...

In [100]:
df.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

In [101]:
df

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,201301010001,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Explosive device defused in Bannu,"" The News ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
1,201301010002,2013,1,1,NaN,0,NaN,95,Iraq,10,...,Casualty numbers for this incident represent a...,"""Deadly bombing leaves destruction in Kirkuk,""...","""Iraq bomb kills one,"" ITN, January 2, 2013.","""Deadly Iraq bombings near Kirkuk - video,"" St...",START Primary Collection,-9,-9,0,-9,"201301010002, 201301010003"
2,201301010003,2013,1,1,NaN,0,NaN,95,Iraq,10,...,Casualty numbers for this incident represent a...,"""Deadly bombing leaves destruction in Kirkuk,""...","""Iraq bomb kills one,"" ITN, January 2, 2013.","""Deadly Iraq bombings near Kirkuk - video,"" St...",START Primary Collection,-9,-9,0,-9,"201301010003, 201301010002"
3,201301010004,2013,1,1,NaN,0,NaN,95,Iraq,10,...,Casualty numbers for this incident conflict ac...,"""2 cops wounded by explosion mid Kirkuk,"" Aswa...","""Iraqi forces arrest al-Qaeda terrorists,"" IRI...","""Policeman killed, another wounded in Kirkuk,""...",START Primary Collection,-9,-9,0,-9,NaN
4,201301010005,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Tragedy averted: 5kg bomb defused near po...","""BDS defuses two bombs in Orangi and Steel Tow...","""Bombs defused in Orangi, Steel Town,"" The New...",START Primary Collection,0,0,0,0,NaN
5,201301010006,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""BDS defuses two bombs in Orangi and Steel Tow...","""Bombs defused in Orangi, Steel Town,"" The New...","""Bombs defused in Orangi, Steel Town,"" Daily T...",START Primary Collection,-9,-9,0,-9,NaN
6,201301010007,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Two officers, driver shot dead,"" Plus News Pa...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
7,201301010008,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Two officers, driver shot dead,"" Plus News Pa...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
8,201301010009,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""70 kg bomb defused in Peshawar,"" Free Press J...","""Blast in Jamrud damages house of anti-polio w...","""Big bomb defused in Peshawar,"" The News Inte...",START Primary Collection,-9,-9,0,-9,NaN
9,201301010012,2013,1,1,NaN,1,NaN,147,Nigeria,11,...,NaN,"""Police Rescue Delta Varsity's Official From K...","""Varsity Staff Kidnapped in Delta,"" Vanguard, ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
10,201301010013,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,There is doubt that this incident meets terror...,"""Policeman gunned down in SITE,"" Plus News Pak...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
11,201301010014,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Charity workers shot dead returning from girl...","""MILITANTS GUN DOWN 7 AID WORKERS IN PAKISTAN,...","""Pakistani Militants Gun Down 7 Aid Workers,"" ...",START Primary Collection,0,0,0,0,NaN
12,201301010015,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""3 cops wounded, officer's house exploded in T...","""3 cops wounded, officer's house exploded in T...",NaN,START Primary Collection,-9,-9,0,-9,"201301010015, 201301010016"
13,201301010016,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""3 cops wounded, officer's house exploded in T...","""3 cops wounded, officer's house exploded in T...","""A policeman injured east of Tikrit.,"" Nationa...",START Primary Collection,-9,-9,0,-9,"201301010016, 201301010015"
14,201301010017,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""3 cops wounded, officer's house exploded in T...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
15,201301010020,2013,1,1,NaN,0,NaN,92,India,6,...,NaN,"""Two more bombs found in Jaisalmer,"" The Times...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
16,201301010022,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""6 people killed in Iraq's violence,"" Xinhua N...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
17,201301010023,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""6 people killed in Iraq's violence,"" Xinhua N...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
18,201301010024,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Two girl students killed in Bara rocket hit,""...","""Two girl students killed in Bara rocket hit,""...","""Tragedy: Two girls killed, five injured by st...",START Primary Collection,-9,-9,0,-9,NaN
19,201301010025,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Truck driver injured in gun attack,"" Daily Ti...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
20,201301010026,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""3 killed in NWA blast, shelling,"" Daily The P...","""Three killed in NWA blast, shelling,"" The New...","""FWO man dies in blast,"" Plus News Pakistan, J...",START Primary Collection,-9,-9,0,-9,NaN
21,201301010027,2013,1,1,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines anger at logging ban murder,"" Qat...","""CENRO official shot dead in Quirino,"" ABS-CBN...","""DENR official shot dead in Quirino province,""...",START Primary Collection,-9,-9,0,-9,NaN
22,201301010029,2013,1,1,NaN,0,NaN,147,Nigeria,11,...,NaN,"""Nigerian forces kill 13 militants,"" CNN, Janu...","""Nigerian army says 14 die in gun battle with ...","""13 suspected militants killed in northern Nig...",START Primary Collection,0,0,0,0,NaN
23,201301010033,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""4 killed, 50 injured as bomb goes off near MQ...","""Pakistan arrests five over polio killings: ...","""1 killed, over 30 injured as bomb goes off ne...",START Primary Collection,0,0,0,0,NaN
24,201301010036,2013,1,1,NaN,0,NaN,95,Iraq,10,...,Casualty numbers for this incident conflict ac...,"""6 people killed in Iraq's violence,"" Xinhua N...","""A soldier killed ,two others injured ,center ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
25,201301010037,2013,1,1,NaN,0,NaN,95,Iraq,10,...,NaN,"""6 people killed in Iraq's violence,"" Xinhua N...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
26,201301020001,2013,1,1,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Attack: Worker's hujra destroyed by twin blas...","""Blast in Jamrud damages house of anti-polio w...","""2 houses damaged in Jamrud blasts,"" Frontier ...",START Primary Collection,-9,-9,0,-9,NaN
27,201301020002,2013,1,2,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Instilling terror: Yet another explosion in U...","""Another explosion in Peshawar varsity,"" Front...","""Bomb jolts Peshawar University,"" Pakistan Tod...",START Primary Collection,-9,-9,0,-9,NaN
28,201301020004,2013,1,2,NaN,0,NaN,147,Nigeria,11,...,NaN,"""Seven dead in Nigerian army clash with insurg...","""Gunmen and security forces clash in Nigeria, ...","""Gunmen and security forces clash in Nigeria, ...",START Primary Collection,0,0,0,0,NaN
29,201301020005,2013,1,3,NaN,0,NaN,4,Afghanistan,6,...,NaN,"""Danish soldier killed in Afghanistan: ministr...","""Danish soldier killed by explosion in Afghani...","""AFGHANISTAN Danish soldier dies,"" The Adverti...",START Primary Collection,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57166,201612310011,2016,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines: BIFF attacks soldiers in North C...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
57167,201612310012,2016,12,31,NaN,0,NaN,19,Bangladesh,6,...,NaN,"""Ruling party lawmaker shot dead in Bangladesh...","""Liton murder: PM blames Jamaat,"" Bangladesh D...","""Gaibandha MP shot dead at home,"" Bangladesh D...",START Primary Collection,0,0,0,0,NaN
57168,201612310013,2016,12,30,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Suicide attack foiled in Rahim Yar Khan; two ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57169,201612310014,2016,12,31,NaN,0,NaN,173,Saudi Arabia,10,...,NaN,"""Rebel fire from Yemen kills Saudi soldier,"" T...","""Saudi Soldier killed due to rebel fire from Y...","""Saudi soldier killed by Houthi fire on Yemen ...",START Primary Collection,1,1,0,1,NaN
57170,201612310015,2016,12,31,NaN,0,NaN,4,Afghanistan,6,...,The victims included Nazia. Casualty numbers c...,"""Wounded bride: All my dreams shattered,"" Pajh...","""Highlights: Pakistan Pashto Press 1 January D...",NaN,START Primary Collection,-9,-9,0,-9,NaN
57171,201612310016,2016,12,31,NaN,0,NaN,34,Burundi,11,...,NaN,"""Grenade explosion injures 8 in church in Buru...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57172,201612310017,2016,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""ANP leader Rahim Barakazi killed in Peshawar,...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57173,201612310019,2016,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Bomb found at Imphal, hospital closed down,"" ...","""Bomb found at Imphal, hospital closed down,"" ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
57174,201612310022,2016,12,31,2016-12-31 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Farah ALP officer wounded in gun attack,"" Paj...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57175,201612310023,2016,12,31,2016-12-31 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Afghanistan: Nangarhar, Logar Clashes Result ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57176,201612310024,2016,12,31,NaN,0,NaN,147,Nigeria,11,...,NaN,"""Nigerian girl, 10, used in suicide bomb attac...","""Suicide bomber, aged 10, blows herself up in ...","""10-year-old girl used as human bomb in Nigeri...",START Primary Collection,0,0,0,0,NaN
57177,201612310025,2016,12,31,2016-12-31 00:00:00,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Security Roundup 1900 GMT 31 December 2...",NaN,NaN,START Primary Collection,0,1,0,1,NaN
57178,201612310026,2016,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Double bomb attack hits crowded Baghdad marke...","""Dozens Killed In Baghdad Blasts Claimed By Is...",NaN,START Primary Collection,-9,-9,0,-9,NaN
57179,201612310027,2016,12,31,NaN,0,NaN,95,Iraq,10,...,Casualty numbers represent a division of the t...,"""Double bomb attack hits crowded Baghdad marke...","""Update: Baghdad bomb attacks kill 30 at eve o...","""28 killed in Baghdad double suicide bombing 2...",START Primary Collection,0,1,0,1,"201612310027, 201612310028"
57180,201612310028,2016,12,31,NaN,0,NaN,95,Iraq,10,...,Casualty numbers represent a division of the t...,"""Double bomb attack hits crowded Baghdad marke...","""Update: Baghdad bomb attacks kill 30 at eve o...","""28 killed in Baghdad double suicide bombing 2...",START Primary Collection,0,1,0,1,"201612310027, 201612310028"
57181,201612310029,2016,12,31,NaN,0,NaN,95,Iraq,10,...,Casualty numbers conflict across sources. Foll...,"""Reuters: Baghdad blasts kill 29 as Mosul figh...","""Update: Baghdad bomb attacks kill 30 at eve o...","""Dozens Killed In Baghdad Blasts Claimed By Is...",START Primary Collection,-9,-9,0,-9,NaN
57182,201612310030,2016,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Update: Baghdad bomb attacks kill 30 at eve o...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57183,201612310031,2016,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""CTS destroys 4 car bombs in eastern Mosul,"" I...",NaN,NaN,START Primary Collection,0,1,0,1,NaN
57184,201612310033,2016,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Two FC Balochistan personnel shot dead in Now...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57185,201612310034,2016,12,31,NaN,0,NaN,4,Afghanistan,6,...,Casualty figures represent a division of the t...,"""Jawzjan clash leaves 2 rebels dead, 8 wounded...",NaN,NaN,START Primary Collection,0,0,0,0,"201612310034, 201612310035, 201612310036, 2016..."
57186,201612310035,2016,12,31,NaN,0,NaN,4,Afghanistan,6,...,Casualty figures represent a division of the t...,"""Jawzjan clash leaves 2 rebels dead, 8 wounded...",NaN,NaN,START Primary Collection,0,0,0,0,"201612310034, 201612310035, 201612310036, 2016..."
57187,201612310036,2016,12,31,NaN,0,NaN,4,Afghanistan,6,...,Casualty figures represent a division of the t...,"""Jawzjan clash leaves 2 rebels dead, 8 wounded...",NaN,NaN,START Primary Collection,0,0,0,0,"201612310034, 201612310035, 201612310036, 2016..."
57188,201612310037,2016,12,31,NaN,0,NaN,4,Afghanistan,6,...,Casualty figures represent a division of the t...,"""Jawzjan clash leaves 2 rebels dead, 8 wounded...",NaN,NaN,START Primary Collection,0,0,0,0,"201612310034, 201612310035, 201612310036, 2016..."
57189,201612310038,2016,12,30,NaN,0,NaN,4,Afghanistan,6,...,"The victims included Commander Shakoor, Noorul...","""Afghansitan: Blast in Jowzjan Province Kills ...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
57190,201612310039,2016,12,31,2016-12-31 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Program Summary: Afghanistan-Pul-e Alam Zinat...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
57191,201612310040,2016,12,31,NaN,0,NaN,146,Niger,11,...,NaN,"""15 soldiers killed, 19 injured in Niger terro...","""Niger: Boko Haram attack kills two soldiers i...",NaN,START Primary Collection,1,1,0,1,NaN
57192,201612310042,2016,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""AFP braces for more BIFF attacks in ARMM,"" Ma...","""Asia: US Army ASD Philippine Terrorist Media ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
57193,201612310043,2016,12,31,NaN,1,NaN,229,Democratic Republic of the Congo,11,...,NaN,"""DRC Armed Forces Dislodge Ugandan LRA Rebels ...",NaN,NaN,START Primary Collection,1,1,0,1,NaN
57194,201612310044,2016,12,31,NaN,0,NaN,130,Mexico,1,...,There is doubt that this incident meets terror...,"""Gunmen shoot at home of Mexican indigenous ri...","""– Gunmen shoot at home of Mexican indigenous ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
57195,201701270001,2016,12,30,NaN,0,NaN,195,Sudan,11,...,There is doubt that this incident meets terror...,"""Rebels To Blame For Nierteti Killing: Central...","""Security deteriorates in West Darfur alongsid...",NaN,START Primary Collection,0,0,0,0,NaN

In [102]:
df.shape

(57196, 135)

In [103]:
df.isnull().sum(axis=0)

eventid                   0
iyear                     0
imonth                    0
iday                      0
approxdate            50401
extended                  0
resolution            57196
country                   0
country_txt               0
region                    0
region_txt                0
provstate                 0
city                      0
latitude                374
longitude               374
specificity               0
vicinity                  0
location              34523
summary                   0
crit1                     0
crit2                     0
crit3                     0
doubtterr                 0
alternative           46767
alternative_txt       46767
multiple                  0
success                   0
suicide                   0
attacktype1               0
attacktype1_txt           0
                      ...
propextent            36728
propextent_txt        36728
propvalue             36728
propcomment           28281
ishostkid                 0
nhostkid              52505
nhostkidus            52505
nhours                55885
ndays                 53816
divert                57149
kidhijcountry         57174
ransom                52505
ransomamt             56907
ransomamtus           56907
ransompaid            56907
ransompaidus          56907
ransomnote            56941
hostkidoutcome        52505
hostkidoutcome_txt    52505
nreleased             52504
addnotes              43698
scite1                    0
scite2                21986
scite3                36113
dbsource                  0
INT_LOG                   0
INT_IDEO                  0
INT_MISC                  0
INT_ANY                   0
related               46841
Length: 135, dtype: int64

In [104]:
data_set = df.dropna(subset=[
'approxdate'  ,
'resolution'  ,
'provstate'  ,
'city'  ,
'latitude'  ,
'longitude'  ,
'specificity'  ,
'location'  ,
'summary'  ,
'alternative'  ,
'alternative_txt'  ,
'propextent'  ,
'propextent_txt'  ,
'propvalue'  ,
'propcomment'  ,
'ishostkid'  ,
'nhostkid'  ,
'nhostkidus'  ,
'nhours'  ,
'ndays'  ,
'divert'  ,
'kidhijcountry'  ,
'ransom'  ,
'ransomamt'  ,
'ransomamtus'  ,
'ransompaid'  ,
'ransompaidus'  ,
'ransomnote'  ,
'hostkidoutcome'  ,
'hostkidoutcome_txt'  ,
'nreleased'  ,
'addnotes'  ,
'scite1'  ,
'scite2'  ,
'scite3' ,
'related','eventid', 'iyear', 'country', 'region', 'crit1', 'crit2', 'crit3', 'doubtterr', 'attacktype1', 'suicide', 'claimed', 'success', 'targtype1', 'gname', 'weaptype1'])

In [105]:
df.claimed.unique().tolist()

[0, 1]

In [106]:
#df.dtypes

In [107]:
#Feature Selection or Feature Engineering
data_set = df[['eventid', 'iyear', 'country', 'region', 'crit1', 'crit2', 'crit3', 'doubtterr', 'attacktype1', 'suicide', 'claimed', 'success', 'targtype1', 'gname', 'weaptype1']]

In [108]:
data_set.head(10)

,eventid,iyear,country,region,crit1,crit2,crit3,doubtterr,attacktype1,suicide,claimed,success,targtype1,gname,weaptype1
0,201301010001,2013,153,6,1,1,1,0,3,0,0,0,3,Unknown,6
1,201301010002,2013,95,10,1,1,1,0,3,0,0,1,14,Unknown,6
2,201301010003,2013,95,10,1,1,1,0,3,0,0,1,3,Unknown,6
3,201301010004,2013,95,10,1,1,1,0,3,0,0,1,3,Unknown,6
4,201301010005,2013,153,6,1,1,1,0,3,0,0,0,14,Tehrik-i-Taliban Pakistan (TTP),6
5,201301010006,2013,153,6,1,1,1,0,3,0,0,0,19,Unknown,6
6,201301010007,2013,153,6,1,1,1,0,2,0,0,1,2,Unknown,5
7,201301010008,2013,153,6,1,1,1,0,1,0,0,1,3,Unknown,5
8,201301010009,2013,153,6,1,1,1,0,3,0,0,0,17,Unknown,6
9,201301010012,2013,147,11,1,1,1,0,6,0,0,1,8,Unknown,5

In [109]:
data_set = data_set.values

In [110]:
#data_set['gname'] = data_set['gname'].astype('category')

In [111]:
#data_set['weaptype1'] = data_set['weaptype1'].astype('category')

In [112]:
#data_set['attacktype1'] = data_set['attacktype1'].astype('category')

In [113]:
#data_set['targtype1'] = data_set['targtype1'].astype('category')

## Target stored in y

In [114]:
y=data_set[['claimed']]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
y.head(100)

## Taking features to predict claimed

In [ ]:
Gtd_features = ['crit1','crit2','crit3','doubtterr',
        'suicide','success']

In [ ]:
X = data_set[Gtd_features].copy()

In [ ]:
X.columns

In [ ]:
y.columns

## Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [ ]:
type(X_train)
type(X_test)
type(y_train)
type(y_test)
X_train.head()
y_train.describe()

## Fit on Train set

In [ ]:
terrorism_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
terrorism_classifier.fit(X_train, y_train)

In [ ]:
type(terrorism_classifier)

## Predict on Test set

In [ ]:
predictions = terrorism_classifier.predict(X_test)

In [ ]:
predictions[:20]

In [ ]:
y_test['claimed'][:10]

## Measuring the accuracy of classifier

In [ ]:
accuracy_score(y_true = y_test, y_pred = predictions)